# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenTTD' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OpenTTD
  pod 'freetype'
  pod 'libpng'
end

post_install do |installer|
  libpng = installer.pods_project.targets.find { |target| target.name == 'libpng' }
  libpng.build_configurations.each do |config|
    config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'PNG_ARM_NEON_OPT=0']
  end
end
