platform :ios, '10.2'

target 'OpenTTD' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OpenTTD
  pod 'freetype'
  pod 'libpng'
  pod 'lzo2', podspec: 'lzo2.podspec'
end

post_install do |installer|
  libpng = installer.pods_project.targets.find { |target| target.name == 'libpng' }
  libpng.build_configurations.each do |config|
    config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'PNG_ARM_NEON_OPT=0']
  end
end
